exchange/fileservice/urls.py
from django.conf.urls import patterns, url, include
from api import FileItemResource

fileitem_resource = FileItemResource()

urlpatterns = patterns(
    '',
    url(r'^api/', include(fileitem_resource.urls)),
)

exchange/storyscapes/urls.py
from django.conf.urls import patterns, url, include
from .views import (save_story, new_story_json,
                    new_chapter_json, draft_view,
                    story_view, story_detail)
from .annotations.views import annotations
from .boxes.views import boxes

from tastypie.api import Api

from api import StoryResource

v1_api = Api(api_name='v1')

v1_api.register(StoryResource())

urlpatterns = patterns(
    '',
    # maploom
    url(r'^story/chapter/new$', new_chapter_json, name='new_chapter'),
    url(r'^story/new$', 'geonode.maps.views.new_map',
        {'template': 'composer/editor.html'}, name='new_story'),
    url(r'^story$', new_story_json,
        name='new_story_json'),
    url(r'^story/(?P<storyid>[^/]+)/save$', save_story,
        name='save_story'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^story/(?P<story_id>[^/]+)/draft$', draft_view,
        {'template': 'composer/editor.html'},
        name='composer-draft-view'),
    url(r'^maps/(?P<mapid>[^/]+)/boxes$', boxes, name='boxes'),
    url(r'^maps/(?P<mapid>[^/]+)/annotations',
        annotations, name='annotations'),
    url(r'^story/(?P<story_id>\d+)/?$', story_detail, name='story_detail'),
    url(r'^story/(?P<storyid>\d+)/view$', story_view, name='story_view'),


)

exchange/thumbnails/urls.py
from django.conf.urls import url

from .views import thumbnail_view
from .tasks import register_post_save_functions

urlpatterns = (
    url(r'^thumbnails/(?P<objectType>maps|documents|layers)/(?P<objectId>.+)$',
        thumbnail_view, name='thumbnail_handler'),
)

register_post_save_functions()

exchange/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 Boundless Spatial
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from maploom.geonode.urls import urlpatterns as maploom_urls
from fileservice.urls import urlpatterns as fileservice_urls
from thumbnails.urls import urlpatterns as thumbnail_urls
from geonode.urls import urlpatterns as geonode_urls
from . import views
from storyscapes.urls import urlpatterns as story_urls

js_info_dict = {
    'packages': ('geonode.layers',),
}

urlpatterns = patterns(
    '',
    url(r'^/?$', views.home_screen, name='home'),
    url(r'^layers/(?P<layername>[^/]*)/metadata_detail$',
        views.layer_metadata_detail, name='layer_metadata_detail'),
    url(r'^layers/(?P<layername>[^/]*)/publish$',
        views.layer_publish, name='layer_publish'),
    url(r'^maps/(?P<mapid>[^/]*)/metadata_detail$', views.map_metadata_detail,
        name='map_metadata_detail'),
    url(r'^wfsproxy/', views.geoserver_reverse_proxy,
        name='geoserver_reverse_proxy'),
    # Redirect help and developer links to the documentation page
    url(r'^help/$', views.documentation_page, name='help'),
    url(r'^developer/$', views.documentation_page, name='developer'),

    url(r'^services/(?P<pk>\d+)/publish$',
        views.publish_service, name='publish_service'),

    url(r'^about/', views.about_page, name='about'),
    url(r'^capabilities/', views.capabilities, name='capabilities'),
)

if settings.ENABLE_SOCIAL_LOGIN is True:
    urlpatterns += [
        url('', include('social_django.urls', namespace='social'))
    ]

# If django-osgeo-importer is enabled...
if 'osgeo_importer' in settings.INSTALLED_APPS:
    # Replace the default Exchange 'layers/upload'
    from osgeo_importer.views import FileAddView
    urlpatterns += [
        url(
            r'^layers/upload$',
            login_required(FileAddView.as_view()),
            name='layer_upload'
        )
    ]
    # Add django-osgeo-importer URLs
    from osgeo_importer.urls import urlpatterns as osgeo_importer_urls
    urlpatterns += osgeo_importer_urls

if settings.STORYSCAPES_ENABLED:
    urlpatterns += story_urls

if 'nearsight' in settings.INSTALLED_APPS:
    from nearsight.urls import urlpatterns as nearsight_urls
    urlpatterns += nearsight_urls

# use combined registry/geonode elastic search rather than geonode search
if settings.ES_SEARCH:
    urlpatterns += [url(r'^api/(?P<resourcetype>base)/search/$',
                        views.elastic_search,
                        name='elastic_search')]
    urlpatterns += [url(r'^api/(?P<resourcetype>documents)/search/$',
                        views.elastic_search,
                        name='elastic_search')]
    urlpatterns += [url(r'^api/(?P<resourcetype>layers)/search/$',
                        views.elastic_search,
                        name='elastic_search')]
    urlpatterns += [url(r'^api/(?P<resourcetype>maps)/search/$',
                        views.elastic_search,
                        name='elastic_search')]
    urlpatterns += [url(r'^api/(?P<resourcetype>registry)/search/$',
                        views.elastic_search,
                        name='elastic_search')]
    urlpatterns += [url(r'^autocomplete',
                        views.empty_page,
                        name='autocomplete_override')]

if 'geonode_anywhere' in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^anywhere/", include("geonode_anywhere.urls")), ]

if 'worm' in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^services/", include("worm.urls")), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += geonode_urls
urlpatterns += maploom_urls
urlpatterns += fileservice_urls
urlpatterns += thumbnail_urls

exchange/core/models.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2016 Boundless Spatial
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.db import models
from solo.models import SingletonModel
from django.conf import settings
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from resizeimage import resizeimage
from django import forms
import os
import uuid
import datetime
from django.db.models import Q
from geonode.base.models import TopicCategory, License
from geonode.base.enumerations import UPDATE_FREQUENCIES
from django.conf import settings


class ThumbnailImage(SingletonModel):
    thumbnail_image = models.ImageField(
        upload_to=os.path.join(settings.MEDIA_ROOT, 'thumbs'),
    )

    def save(self, *args, **kwargs):
        pil_image_obj = Image.open(self.thumbnail_image)
        new_image = resizeimage.resize_cover(
            pil_image_obj,
            [250, 150],
            validate=False
        )

        new_image_io = BytesIO()
        new_image.save(new_image_io, format='PNG')

        temp_name = self.thumbnail_image.name
        self.thumbnail_image.delete(save=False)

        self.thumbnail_image.save(
            temp_name,
            content=ContentFile(new_image_io.getvalue()),
            save=False
        )

        super(ThumbnailImage, self).save(*args, **kwargs)


class ThumbnailImageForm(forms.Form):
    thumbnail_image = forms.FileField(
        label='Select a file',
    )


def get_classifications():
        return [(x, str(x)) for x in getattr(
            settings, 'CLASSIFICATION_LEVELS', [])]


def get_caveats():
        return [(x, str(x)) for x in getattr(settings, 'CAVEATS', [])]


def get_provenances():
        default = [('Commodity', 'Commodity'),
                   ('Crowd-sourced data', 'Crowd-sourced data'),
                   ('Derived by trusted agents ',
                    'Derived by trusted agents '),
                   ('Open Source', 'Open Source'),
                   ('Structured Observations (SOM)',
                    'Structured Observations (SOM)'),
                   ('Unknown', 'Unknown')]

        provenance_choices = [(x, str(x)) for x in getattr(
            settings, 'REGISTRY_PROVENANCE_CHOICES', [])]

        return provenance_choices + default


class CSWRecord(models.Model):
    # Registry requires a UUID for all new records
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    status = models.CharField(max_length=128, default='Unknown')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="csw_records_created")

    category_choices = (
        ('Air', 'Air (Aero)'),
        ('Intelligence', 'Intelligence'),
        ('Elevation', 'Elevation'),
        ('HumanGeog', 'Human Geography'),
        ('Basemaps', 'Basemaps'),
        ('Space', 'Space'),
        ('Land', 'Land (Topo)'),
        ('Targeting', 'Targeting'),
        ('NamesBoundaries', 'Names & Boundaries'),
        ('MapsCharts', 'NGA Standard Maps & Charts'),
        ('Sea', 'Sea (Maritime)'),
        ('Imagery', 'Imagery/Collections'),
        ('Geomatics', 'Geodesy/Geodetics Geomatics'),
        ('Weather', 'Weather')
    )

    classification = models.CharField(
        max_length=128, blank=True, choices=get_classifications())
    releasability = models.CharField(
        max_length=128, blank=True, choices=get_caveats())
    title = models.CharField(max_length=328, blank=False)
    short_name = models.CharField(max_length=328, blank=True)
    modified = models.DateField(default=datetime.date.today, blank=False)
    created = models.DateField(default=datetime.date.today, blank=False)
    registered = models.DateField(default=datetime.date.today, blank=False)
    # 'creator' is assumed to be distinct from logged-in User here
    creator = models.CharField(
        max_length=328, blank=True, verbose_name='Agency')
    record_type = models.CharField(max_length=128, blank=True)
    alternative = models.CharField(max_length=128, blank=True)
    abstract = models.TextField(blank=True)
    source = models.URLField(
        max_length=512, blank=False, verbose_name='Service Endpoint')
    relation = models.CharField(max_length=128, blank=True)
    record_format = models.CharField(max_length=128, blank=True)
    srid = models.CharField(max_length=255, default='EPSG:4326')
    bbox_upper_corner = models.CharField(max_length=128,
                                         default="85.0 180",
                                         blank=True)
    bbox_lower_corner = models.CharField(max_length=128,
                                         default="-85.0 -180",
                                         blank=True)
    contact_email = models.CharField(max_length=128, blank=True)
    contact_phone = models.CharField(max_length=128, blank=True)
    contact_position = models.CharField(max_length=128, blank=True)
    contact_address_type = models.CharField(
        max_length=128, blank=True, choices=(
            ('Physical', 'Physical'), ('Postal', 'Postal')))
    contact_address = models.CharField(max_length=128, blank=True)
    contact_city = models.CharField(max_length=128, blank=True)
    contact_state = models.CharField(max_length=2, blank=True)
    contact_country = models.CharField(max_length=128, blank=True)
    contact_zip = models.CharField(max_length=128, blank=True)
    provenance = models.CharField(
        max_length=100, blank=True, choices=get_provenances())
    gold = models.BooleanField(max_length=128, default=False, blank=True)
    category = models.CharField(max_length=128, choices=category_choices,
                                blank=True)
    maintenance_frequency = models.CharField(
        'maintenance frequency', max_length=255, choices=UPDATE_FREQUENCIES,
        blank=True, null=True,
        help_text='Frequency with which modifications and deletions are made '
                  'to the data after it is first produced')
    license = models.ForeignKey(License, null=True, blank=True,
                                verbose_name='License',
                                help_text='License of the dataset')
    keywords = models.CharField(max_length=128, blank=True)

    fees = models.CharField(max_length=1000, null=True, blank=True)
    topic_category = models.ForeignKey(
        TopicCategory, null=True, blank=True, limit_choices_to=Q(
            is_choice=True))
    status_message = models.TextField(blank=True)

    @property
    def contact_information(self):
        """Returns formatted contact information."""
        return "Email: {}\nPhone: {}".format(
            self.contact_email, self.contact_phone)

    class Meta(object):
        verbose_name = 'CSW Record'
        verbose_name_plural = 'CSW Records'
        ordering = ['-modified', 'status', 'title']


class CSWRecordReference(models.Model):
    scheme_choices = (('ESRI:AIMS--http-get-map', 'MapServer'),
                      ('ESRI:AIMS--http-get-feature', 'FeatureServer'),
                      ('ESRI:AIMS--http-get-image', 'ImageServer'),
                      ('WWW:LINK-1.0-http--json', 'JSON'),
                      ('OGC:KML', 'KML'),
                      ('WWW:LINK-1.0-http--rss', 'RSS'),
                      ('WWW:DOWNLOAD', 'SHAPE'),
                      ('WWW:LINK-1.0-http--soap', 'SOAP'),
                      ('OGC:WCS', 'WCS'),
                      ('OGC:WFS', 'WFS'),
                      ('OGC:CS-W', 'CSW'),
                      ('OGC:WMS', 'WMS'),
                      ('OGC:WPS', 'WPS'))
    record = models.ForeignKey(CSWRecord, related_name="references")
    scheme = models.CharField(
        verbose_name='Service Type', choices=scheme_choices, max_length=100)
    url = models.URLField(max_length=512, blank=False)

exchange/thumbnails/views.py
#
# There is only one view for the Thumbnail API.
#
# When the view is called with a GET request it returns
# either a missing thumbnail image *or* the image stored in the database.
#


from django.http import HttpResponse

from base64 import b64decode
import imghdr
import os

from .models import Thumbnail, save_thumbnail

# cache the missing thumbnail for missing images.
TEST_DIR = os.path.dirname(__file__)
MISSING_THUMB = open(
    os.path.join(TEST_DIR, 'static/missing_thumb.png'), 'r').read()


def thumbnail_view(request, objectType, objectId):
    global MISSING_THUMB, ID_PATTERN

    thumb = None
    try:
        thumb = Thumbnail.objects.get(object_type=objectType,
                                      object_id=objectId)
    except Thumbnail.DoesNotExist:
        # move along, the code tests for None later.
        pass

    if(request.method == 'GET'):
        # if the thumb is not None, return it.
        if(thumb is not None):
            return HttpResponse(thumb.thumbnail_img,
                                content_type=thumb.thumbnail_mime)

        # else return the missing thumbnail.
        return HttpResponse(MISSING_THUMB, content_type='image/png')
    elif(request.method == 'POST'):
        body_len = len(request.body)

        # ensure the thumbnail is < 400kb.
        # This is an arbitrary check I've added, it could be
        # adjusted easily.
        max_bytes = 400000
        if(body_len > max_bytes):
            return HttpResponse(status=400, content='Thumbnail too large.')

        image_bytes = request.body
        # check to see if the image has been uploaded as a base64
        #  image.
        if(request.body[0:22] == 'data:image/png;base64,'):
            image_bytes = b64decode(request.body[22:])

        image_type = imghdr.what('', h=image_bytes)
        if(image_type is None):
            return HttpResponse(status=400, content='Bad thumbnail format.')

        # if the thumbnail does not exist, create a new one.
        save_thumbnail(
            objectType, objectId, 'image/' + image_type, image_bytes, False)

        # return a success message.
        return HttpResponse(status=201)

exchange/templates/services/service_edit.html
{% extends "services/services_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block head %}
{{ block.super }}


{% endblock %}

{% block title %} Edit Service - {{ block.super }} {% endblock %}

{% block body %}
<div class="page-header">
  <h2>{% trans "Edit Service" %}</h2>
</div>
<form method="POST" id="service_edit_form">
  {% csrf_token %}
  {{ service_form|as_bootstrap }}


  <table id="tblReferences" class="table">
                    {{ cswrecordreference.management_form }}

                    {% for form in cswrecordreference.forms %}
                    {% if forloop.first %}
                    <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                        <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                        <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                            {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field }}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>


  <div class="grid-spacer">
      <a href="javascript:history.back()" class="btn btn-default">{% trans "Cancel" %}</a>
    <input type="submit" class="btn btn-primary" value="{% trans "Save" %}"/>
  </div>
</form>
{% endblock %}

exchange/templates/services/service_register.html
{% extends "services/services_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block head %}
{{ block.super }}
{% endblock %}

{% block title %} Register Service - {{ block.super }} {% endblock %}

{% block body_outer %}
<div class="page-header">
    <a href="{% url "services" %}" class="btn btn-primary pull-right">{% trans "Return to List" %}</a>
    <h2>{% trans "Register New Service" %}</h2>
</div>
<div class="container">
    <div id="info" class="alert alert-info" style="display:none;"></div>
    <div id="warning" class="alert alert-warning" style="display:none;"></div>
    <div id="success" class="alert alert-success" style="display:none;"> {%  trans "Service has been imported successfully!" %}</div>
    <div id="error" class="alert alert-danger" style="display:none;"></div>
    <form method="POST" id="service_register_form">
        {% csrf_token %}
        {{ create_service_form|as_bootstrap }}
        <input type="submit" class="btn btn-primary pull-left" id="submit_button" value="{% trans "Submit" %}" />
    </form>
</div>
<br/>
<div class="container">
    <div id="responseDiv" style="display:none;">
        <h4>{%  trans "Service details:" %}</h4>
    </div>

    <div id="tableDiv" style="display:none;">
        <p>{%  trans "The following layers can be published:" %}</p>
        <table id="dataTable" class="table"></table>
    </div>
</div>
{% endblock %}
{% block extra_script %}
{{ block.super }}
<script type="text/javascript">
    $( document ).ready(function() {
        var intervalID;
        function checkName(){
            var service_name_regexp = new RegExp('^[a-zA-Z]+[a-zA-Z0-9-_\.]*$');
            if(!service_name_regexp.test($("#id_name").val())) {
                $("#warning").html("Service name must start with a letter, followed by letters, numbers, or the characters: . - _").show();
                $("#submit_button").prop("disabled",false);
                return false;
            }else{
                $("#warning").hide();
                return true;
            }
        }

        function checkSupportedEsriType(){
            var url = $("#id_url").val().toLowerCase();
            if(url.indexOf('rest/services') >= 0 && url.indexOf('featureserver') >=0) {
                $("#warning").html("Please enter a valid MapServer or ImageServer service url.").show();
                $("#submit_button").prop("disabled",false);
                return false;
            }else{
                $("#warning").hide();
                return true;
            }
        }

        function checkSupportedEsriType(){
            var url = $("#id_url").val().toLowerCase();
            if(url.indexOf('rest/services') >= 0 && url.indexOf('featureserver') >=0) {
                $("#warning").html("Please enter a valid MapServer or ImageServer service url.").show();
                $("#submit_button").prop("disabled",false);
                return false;
            }else{
                $("#warning").hide();
                return true;
            }
        }

        $("#service_register_form").submit(function(e) {
            if(checkName() && checkSupportedEsriType()) {
                $("#info").html("<img src='/static/geonode/img/loading.gif'/>&nbsp; Importing service, please wait...").show();
                $(".result").remove();
                $("#tableDiv").hide();
                $("#warning").hide();
                $("#dataTable").html("");
                $("#success").hide();
                $("#error").hide();
                $("#submit_button").prop("disabled", true);
                e.preventDefault();
                var url = $("#service_register_form").attr("action");

                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "json",
                    data: $("#service_register_form").serialize(), // serializes the form's elements.
                    progress: function (jqXHR, progressEvent) {
                        if (progressEvent.lengthComputable) {
                            console.log("Importing service and layers - " + (Math.round(progressEvent.loaded / progressEvent.total * 100)) + "%");
                        } else {
                            console.log("Importing service and layers...");
                        }
                    },
                    success: function (data) {
                        $("#responseDiv").html("");

                        if (data.job_id){
                            intervalID = setInterval(function() {
                                $.get('/services/registration/'+ data.job_id + '/status', function(data) {
                                    if(data.status === 'completed'){
                                        clearInterval(intervalID);
                                        $("#info").hide();
                                        $("#submit_button").prop("disabled", false);
                                        var hasSuccess = false;
                                        var error_count = 0;
                                        var layer_count = 0;

                                        if (data.result) {

                                            for (var item in data.result) {
                                                if (data.result[item].service_id) {
                                                    hasSuccess = true;

                                                    if (data.result[item].available_layers) {
                                                        layer_count += data.result[item].available_layers.length;
                                                    }

                                                } else {
                                                    error_count++;
                                                    $('<div>').attr("class", "result").text(data.result[item].msg).appendTo("#responseDiv");
                                                }

                                                $("#responseDiv").show();
                                            }

                                            if (error_count == 0) {
                                                if (data.result.length == 1) {
                                                    $('#success').show();
                                                    setTimeout(function () {
                                                        window.location = "/services/" + data.result[item].service_id;
                                                    }, 1000);
                                                } else {
                                                    $("#success").html('Successfully imported ' + layer_count + ' layers from ' + data.result.length + ' services.');
                                                    $('#success').show();
                                                    setTimeout(function () {
                                                        window.location = "/services/";
                                                    }, 1000);
                                                }

                                            } else if (error_count < data.result.length) {
                                                $("#warning").html(layer_count + ' layers successfully imported, however, there were ' + error_count + ' errors encountered while processing ' + data.result.length + ' services. Please see below for details.');
                                                $("#warning").show();
                                            }
                                        }else{
                                            $("#warning").html('Unable to resolve any layers from the service type. Please check the Service Url and Service Type.');
                                            $("#warning").show();
                                        }
                                    } else  if(data.status === 'failed') {
                                        clearInterval(intervalID);
                                        $("#error").html('An unexpected error has occurred, please try again later.');
                                        $("#error").show();
                                        $("#info").hide();
                                        $("#responseDiv").html("");
                                    }
                                } );
                            }, 1000);
                        }
                        else{
                            $("#warning").html('Unable to resolve any layers from the service type. Please check the Service Url and Service Type.');
                            $("#warning").show();
                            $("#submit_button").prop("disabled", false);
                        }
                    },
                    error: function (data) {
                        $("#submit_button").prop("disabled", false);
                        if (data.status == 500) {
                            console.error(data.responseText);
                        }
                        $("#error").html('Unable to access the service provider. Please check the Service Url and Service Type.');
                        $("#error").show();
                        $("#info").hide();
                        $("#responseDiv").html("");
                    }
                });
            }
            return false; // avoid to execute the actual submit of the form.
        });

    });

</script>
{% endblock %}